/-
Copyright (c) 2026 Ben Keene. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ben Keene

Statement of record for the Palomar submission: the first Betti number of a
four-generated numerical semigroup ring is at most twice its width.
-/
import Mathlib

/-!
# A sharp linear bound for the first Betti number of four-generated numerical semigroups

Let `n 0 < n 1 < n 2 < n 3` be positive integers with greatest common divisor `1` which
*minimally* generate the numerical semigroup `S = ⟨n 0, n 1, n 2, n 3⟩` (no generator is a
sum of copies of the others).  The toric ideal `I` of `S` over a field `K` is the kernel of
`K[X₀, X₁, X₂, X₃] → K[t]`, `Xᵢ ↦ t ^ (n i)`; its minimal number of generators `μ(I)` is the
first Betti number `β₁` of `K[S]`.  Write `w = n 3 - n 0` for the width of `S` and
`g = gcd (n 1 - n 0, n 2 - n 0, n 3 - n 0)`.

* `SemigroupBetti.beta1_le_two_mul_normalizedWidth`: `μ(I) ≤ 2 * (w / g)`.
* `SemigroupBetti.beta1_le_two_mul_width`: `μ(I) ≤ 2 * w` (the form stated in the paper).

The conjectured bound in the literature (Herzog–Stamate 2014; Caviglia–Moscariello–Sammartano
2024) was `w.choose 2 + w`, i.e. `(w+1).choose 2`; the bound `2w` is sharp for every `w ≥ 4`.
Both theorems are stated with `Submodule.spanRank` (a cardinal), so no truncation is involved.
-/

namespace SemigroupBetti

open MvPolynomial

/-- The toric ideal of the monoid generated by `n 0, …, n 3`: the kernel of the `K`-algebra map
`K[X₀,…,X₃] → K[t]` sending `X i` to `t ^ n i`. -/
noncomputable def toricIdeal (K : Type*) [Field K] (n : Fin 4 → ℕ) :
    Ideal (MvPolynomial (Fin 4) K) :=
  RingHom.ker (MvPolynomial.aeval (fun i => (Polynomial.X : Polynomial K) ^ n i)).toRingHom

/-- `n` minimally generates its monoid: no `n i` lies in the submonoid generated by the others. -/
def MinimallyGenerates (n : Fin 4 → ℕ) : Prop :=
  ∀ i : Fin 4, n i ∉ AddSubmonoid.closure (n '' {j | j ≠ i})

/-- The normalized width `w / gcd(a, b, w)` where `(a, b, w) = (n 1 - n 0, n 2 - n 0, n 3 - n 0)`. -/
def normalizedWidth (n : Fin 4 → ℕ) : ℕ :=
  (n 3 - n 0) / Nat.gcd (n 1 - n 0) (Nat.gcd (n 2 - n 0) (n 3 - n 0))

/-- **Main theorem.** For a minimally four-generated numerical semigroup, the first Betti number
is at most `2W`, `W` the normalized width. -/
theorem beta1_le_two_mul_normalizedWidth (K : Type*) [Field K] (n : Fin 4 → ℕ)
    (hpos : 0 < n 0) (hmono : StrictMono n) (hgcd : Finset.univ.gcd n = 1)
    (hmin : MinimallyGenerates n) :
    (toricIdeal K n).spanRank ≤ (2 * normalizedWidth n : ℕ) := by
  sorry

/-- The first Betti number is at most twice the width. -/
theorem beta1_le_two_mul_width (K : Type*) [Field K] (n : Fin 4 → ℕ)
    (hpos : 0 < n 0) (hmono : StrictMono n) (hgcd : Finset.univ.gcd n = 1)
    (hmin : MinimallyGenerates n) :
    (toricIdeal K n).spanRank ≤ (2 * (n 3 - n 0) : ℕ) := by
  sorry

end SemigroupBetti
