/-
Copyright (c) 2026 Ben Keene. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ben Keene
-/
import SemigroupBetti

/-!
# Solutions to the Challenge

The declarations of `Challenge.lean`, restated verbatim (definitions `toricIdeal`,
`MinimallyGenerates`, `normalizedWidth` and the two theorem statements) and proved.  As in the
erdos266 submission, this module does not import `Challenge`; the comparator checks that the
statements and the definitions they use agree with `Challenge.lean`.

Each theorem is a thin bridge:
* `GenData.ofChallenge` turns the hypotheses into generator data `G` with `G.n = n`;
* `GenData.spanRank_le_beta1_of_n_eq` (Lemma 0, `SemigroupBetti/Bridge.lean`) gives
  `μ(I) ≤ β₁`, where `β₁` is the combinatorial first Betti number;
* `GenData.beta1_le_two_W` / `GenData.beta1_le_two_w` (`SemigroupBetti/Main.lean`) bound `β₁`.
-/

namespace SemigroupBetti

open MvPolynomial

/-- The toric ideal of the monoid generated by `n 0, …, n 3`: the kernel of the `K`-algebra map
`K[X₀,…,X₃] → K[t]` sending `X i` to `t ^ n i`. -/
noncomputable def toricIdeal (K : Type*) [Field K] (n : Fin 4 → ℕ) :
    Ideal (MvPolynomial (Fin 4) K) :=
  RingHom.ker (MvPolynomial.aeval (fun i => (Polynomial.X : Polynomial K) ^ n i)).toRingHom

/-- `n` minimally generates its monoid: no `n i` lies in the submonoid generated by the others. -/
def MinimallyGenerates (n : Fin 4 → ℕ) : Prop :=
  ∀ i : Fin 4, n i ∉ AddSubmonoid.closure (n '' {j | j ≠ i})

/-- The normalized width `w / gcd(a, b, w)` where `(a, b, w) = (n 1 - n 0, n 2 - n 0, n 3 - n 0)`. -/
def normalizedWidth (n : Fin 4 → ℕ) : ℕ :=
  (n 3 - n 0) / Nat.gcd (n 1 - n 0) (Nat.gcd (n 2 - n 0) (n 3 - n 0))

/-- **Main theorem.** For a minimally four-generated numerical semigroup, the first Betti number
is at most `2W`, `W` the normalized width. -/
theorem beta1_le_two_mul_normalizedWidth (K : Type*) [Field K] (n : Fin 4 → ℕ)
    (hpos : 0 < n 0) (hmono : StrictMono n) (hgcd : Finset.univ.gcd n = 1)
    (hmin : MinimallyGenerates n) :
    (toricIdeal K n).spanRank ≤ (2 * normalizedWidth n : ℕ) := by
  let G := GenData.ofChallenge n hpos hmono hgcd hmin
  have hb : (toricIdeal K n).spanRank ≤ (G.beta1 : Cardinal) :=
    G.spanRank_le_beta1_of_n_eq K (GenData.ofChallenge_n n hpos hmono hgcd hmin)
  have hW : normalizedWidth n = G.W := rfl
  refine hb.trans ?_
  rw [hW]
  exact_mod_cast G.beta1_le_two_W

/-- The first Betti number is at most twice the width. -/
theorem beta1_le_two_mul_width (K : Type*) [Field K] (n : Fin 4 → ℕ)
    (hpos : 0 < n 0) (hmono : StrictMono n) (hgcd : Finset.univ.gcd n = 1)
    (hmin : MinimallyGenerates n) :
    (toricIdeal K n).spanRank ≤ (2 * (n 3 - n 0) : ℕ) := by
  let G := GenData.ofChallenge n hpos hmono hgcd hmin
  have hb : (toricIdeal K n).spanRank ≤ (G.beta1 : Cardinal) :=
    G.spanRank_le_beta1_of_n_eq K (GenData.ofChallenge_n n hpos hmono hgcd hmin)
  have hw : n 3 - n 0 = G.w := rfl
  refine hb.trans ?_
  rw [hw]
  exact_mod_cast G.beta1_le_two_w

end SemigroupBetti
